# Generated by Django 4.0.3 on 2022-03-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_reservas_equipamentos', '0002_alter_dados_linha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
