# Generated by Django 4.0.3 on 2022-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_reservas_equipamentos', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosreserva',
            name='data_reserva',
            field=models.CharField(default=0, max_length=11, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
