# Generated by Django 4.0.3 on 2022-03-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_reservas_equipamentos', '0005_dadosreserva_data_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosReserva',
        ),
    ]
