# Generated by Django 4.0.3 on 2022-06-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_reservas_equipamentos', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosreserva',
            name='horario',
            field=models.CharField(max_length=15, verbose_name='Horario'),
        ),
    ]
